CREATE TABLE `USER` (
  `USER_SEQ` int NOT NULL AUTO_INCREMENT,
  `USER_ID` varchar(100) NOT NULL,
  `USER_PASSWORD` varchar(500) NOT NULL,
  `USER_NAME` varchar(100) NOT NULL,
  `USER_PHONE1` int NOT NULL,
  `USER_PHONE2` int NOT NULL,
  `USER_PHONE3` int NOT NULL,
  `USER_ZIPCODE` varchar(50) NOT NULL,
  `USER_ADD` varchar(500) NOT NULL,
  `USER_DETAIL_ADD` varchar(500) NOT NULL,
  `USER_EMAIL` varchar(500) NOT NULL,
  `USER_REG_DATE` datetime NOT NULL,
  PRIMARY KEY (`USER_SEQ`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb3 COMMENT='유저정보 테이블'

CREATE TABLE `BOARD` (
  `BOARD_SEQ` int NOT NULL AUTO_INCREMENT,
  `USER_SEQ` int DEFAULT NULL,
  `TITLE` varchar(500) DEFAULT NULL,
  `CONTENT` varchar(1000) DEFAULT NULL,
  `FIRST_UPDATE` datetime DEFAULT NULL,
  `LAST_UPDATE` datetime DEFAULT NULL,
  `IP` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`BOARD_SEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3